### ISSUE TITLE
Resolving Blank Fields to Undefined

### ISSUE THREAD

**Issue by jpoles1** [wdavidw/node-csv-parse#101]
So far as I can tell, there is no built-in parameter which allows fields with no content to be resolved to a value of undefined, rather than an empty string (""). This would be quite helpful.

For instance, the row:
3,support,,1
becomes:
[3,support,"",1] but I want [3,support,undefined,1]

This can be done manually after parsing, but this is not as clean.

**Comment by wdavidw** [comment]
Feel free to add a pull request, u could add an option "empty_value" which equals to the substituted value.

**Comment by jpoles1** [comment]
Ok, I will look into doing so when I have a bit of time!

**Comment by wdavidw** [comment]
closing, feel free to re-open if necessary
