### ISSUE TITLE
Use backslash as escape char with no quotes?

### ISSUE THREAD

**Issue by mynameistechno** [wdavidw/node-csv-parse#102]
Is this possible?

``` javascript

let csvParseSync = require('csv-parse/lib/sync');
const assert = require('assert');

assert.deepEqual(csvParseSync('a,\,b\,,c'), [['a', ',b,', 'c']])

```

It returns `[ [ 'a', '', 'b', '', 'c' ] ]` instead of the expected. I've tried various option configurations to no avail. I'm probably doing something wrong. Thanks in advance!

**Comment by mynameistechno** [comment]
Might be related to #101

**Comment by wdavidw** [comment]
The behavior in CSV is to quote the field. Have a look at [escape tests](https://github.com/wdavidw/node-csv-parse/blob/master/test/options.escape.coffee) and re-open if necessary.
