### ISSUE TITLE
skip_empty_lines is not working

### ISSUE THREAD

**Issue by RaghavendhraK** [wdavidw/node-csv-parse#107]
csvFile contains
```
First name,Surname,Community Group or Organisation,Address,Address 2,Postcode,Phone number,Mobile number,Email Address,Date of Birth (01/01/YEAR),Gender,Previous regular volunteer? (Y/N),Joining Date  (01/04/2015 etc),Quarter Joined,ACE Member
aaron,powell,mill park,,,cf54dj,,,,,,Yes,2010-13,Existing,
,,,,,,,,,,,,,,
abbie,andrews,,,,cf55bw,123456,9874561, Abbiee31@hotmail.co.uk,,,no,2010-13,Existing,no
```
```
var options = {
     skip_empty_lines: true,
     trim: true
 }
fs.readFile(csvFile, 'utf8', (e, csvData)=>{
    parse(csvData, options, (e, data)=>{
        console.log(data)
    });
});
```
But data includes the empty lines also .i.e., [ '', '', '', '', '', '', '', '', '', '', '', '', '', '', '' ].
Am I doing anything wrong here?

**Comment by wdavidw** [comment]
"\n,,,,\n" isnt considered an empty line but a line filled with empty values, "\n \t\n" is an empty line. If you need this behavior, a new property would need to be created, something like "skip_lines_with_empty_values". I'll be happy to review a pull request if you wish to implement it.
