### ISSUE TITLE
HELP: How to parse csv file inconsistent columns

### ISSUE THREAD

**Issue by morfies** [wdavidw/node-csv-parse#109]
Hi, I need to parse a csv file with first line only has one value while all others have 63 columns.
If I set `options.column` to a function returns null, the parser can parse out all other lines but the first line is lost, if I set `options.column` to other values, parser will throw error.

thanks

**Comment by wdavidw** [comment]
try the option "relax_column_count: true"

**Comment by morfies** [comment]
wow, by removing `column` and add `relax_column_count: true`, I got what I wanted.
Thanks very much for this handy module.
