### ISSUE TITLE
UTF-8 characters are not read properly

### ISSUE THREAD

**Issue by molerat619** [wdavidw/node-csv-parse#111]
I have this string in a cell in csv `muss ausgefüllt sein.` and after reading it, I get `muss ausgef�llt sein.`.

Basically, this is my code:

```
var fs = require('fs');
var parse = require('csv-parse');
var _ = require('lodash');
import {Translation} from '../sqldb';

// columns: true makes csv-parse spit out objects instead of arrays
var parser = parse({delimiter: ';', columns: true}, function(err, data){
  _.each(data, function(translation){
    if(translation != ""){
      Translation.findById(translation.id).then(function(result){
        if(!_.isNull(result)){
          result.updateAttributes(translation).then(function(){
            console.log('saved ' + translation.key);
          });
        }
      });
    }
  });
});

fs.createReadStream(__dirname+'/../uploads/translations/translations.csv').pipe(parser);
```

What's the problem?

**Comment by wdavidw** [comment]
your sample works perfectly with me. make sure your terminal is configured in utf8. if you have any doubte, dump data into a file and compare it with the source file.

**Comment by molerat619** [comment]
no special utf8 treatment needed for the parser? the result that is saved into the database has the same character problem.

**Comment by wdavidw** [comment]
no, nodejs is utf8 by default, the parser isnt involved. Are u sure your source file is utf8 encoded? try 

```bash
echo 'hören' > test.csv` 
openssl md5 test.csv 
MD5(test.csv)= ae3dc4d1c1c5482b9828d5292a5df371
```

and run

```
parse = require('.')
fs = require('fs');
fs.createReadStream('test.csv').pipe(parse(function(err, data){
  console.log(data);
}));
```

**Comment by molerat619** [comment]
@wdavidw thanks for your time. I fixed it now. I don't know what the problem was though, because I have tried many different things. Anyway I appreciate your help and this post confirms to other people out there that utf8 really works fine with this package.
