### ISSUE TITLE
2-Character rowDelimiter Not Accepted

### ISSUE THREAD

**Issue by teschste** [wdavidw/node-csv-parse#112]
When parsing a Windows CSV file, the lines are separated by a \r\n combination but when I use csv-parse against those records, I get unexpected results as follows:

- With no rowDelimiter specified (presumably using the default 'auto'), the rows are parsed on \r and the \n is appended to the front of each row after the first.
- With rowDelimiter: 'auto', or 'windows', or 'unix', or 'unicode' specified, the rows are not parsed at all (all records are returned in the first array element).
- With rowDelimiter: '\r\n' specified, I get the same results as above, the rows are not parsed at all.
- Specifying rowDelimiter: '\r' gives the same results as if no rowDelimiter was specified (so at least it works...sort of).
- Specifying rowDelimiter: '\n' gives the expected opposite effect of no rowDelimiter being specified (the last record of each row has \r appended to the end).

I am currently working around the issue by replacing all \r\n in my input with \r only but the documentation for csv-parse implies multiple character delimiters are supported (rowDelimiter (**chars**|constant)), so this should be fixed.

Thanks!

**Comment by teschste** [comment]
This issue can be deleted.

It turns out that the file I was reading and parsing had been created on a Windows server in utf-16 (I have no control over this) but I expected and read the file using utf-8 or ascii, which caused the issue described above.  Changing the file read process to use utf-16 resolved the problem and the csv parser now works perfectly.

Sorry for the confusion.

**Comment by wdavidw** [comment]
great
