### ISSUE TITLE
Multiple row delimiters

### ISSUE THREAD

**Issue by vamzz1** [wdavidw/node-csv-parse#118]
Issue: https://github.com/wdavidw/node-csv/issues/216.

- I need permission to push my branch.

**Comment by wdavidw** [comment]
For sure, you would need to be a commiter to push directly to this repo. You'll need to create a [pull request](https://help.github.com/articles/about-pull-requests/)

**Comment by vamzz1** [comment]
I'm unable to push the branch itself to create the pull request. Am I missing something here? I can't create a pull request without pushing the branch, can I?

**Comment by wdavidw** [comment]
If I remember well, you need to fork this repository, work on your fork, commit, push and make a pull request from there
