### ISSUE TITLE
Trailing whitespace and empty headers

### ISSUE THREAD

**Issue by gmisra** [wdavidw/node-csv-parse#120]
Under the following conditions, 
- Header row included
- Header row ends with a delimiter + whitespace
- Last data row is not an empty line
- Last data row ends with a delimiter + whitespace
- The ```trim``` option is enabled.

The parser will return an error, that the last row does not have the correct number of columns. It appears that the trim behavior is inconsistent between the header row and the last data row in the absence of a trailing newline. This may be an edge case, or this may be the desired behavior, but it was surprising to me. Please feel free to close this issue if this is the desired behavior.

_Sample Code_ (using csv-parse@1.1.7)
```
const parse = require('csv-parse');

const opts = {
  delimiter: ',',
  columns: true,
  trim: true,
  skip_empty_lines: true
};

const testA = 'h1,h2,h3, \n1,2,3, \n4,5,6, \n';
const testB = 'h1,h2,h3, \n1,2,3, \n4,5,6, ';

function test(desc, payload) {
  parse(payload, opts, function (err, res) {
    if (err) {
      console.log(`${desc}: ${err}`);
    } else {
      console.log(`${desc}: Success!`);
    }
  });
}

test('TEST A', testA);
test('TEST B', testB);
```

**Comment by wdavidw** [comment]
thanks for reporting

**Comment by gmisra** [comment]
Thanks, can you clarify whether this is a bug or expected behavior? We have an external data source that provides files formatted like "testB" above. We currently append an extra newline, and I would like to document whether that is a workaround, or the correct behavior for using csv-parse.

**Comment by wdavidw** [comment]
Now that there is a test enforcing it, I would call it a feature.

**Comment by gmisra** [comment]
:thumbsup:
