### ISSUE TITLE
Empty lines not skipped

### ISSUE THREAD

**Issue by tulika-agr** [wdavidw/node-csv-parse#122]
var csv = require("csv")
var report = "Date,Value\n" +
            "2016/02/11,5341022\n" +
            "2016/02/12,4771\n" +
            "2016/02/12,5341022\n\n\n";
var csvOpts = {columns: true, skip_empty_lines: true, trim: true, auto_parse: true};
csv.parse(report, csvOpts, function(err, data) {
    console.log(data);
});
The above code prints 4 objects instead of 3. The last one has a single field "Date"
0: Object {Date: "2016/02/11", …}
1: Object {Date: "2016/02/12", …}
2: Object {Date: "2016/02/12", …}
3: Object {Date: ""…}

**Comment by Jacob-Lynch** [comment]
I just noticed this same issue in our setup and came here to note it, thanks.  Although in our case it doesn't look like we have any empty lines at the end, it just simply passes an empty object for the last row parsed (after the last valid row).

**Comment by wdavidw** [comment]
seems related to one of the latest commit, will look soon

**Comment by Jacob-Lynch** [comment]
Yes, I reverted to 1.1.0, and it's back to normal.

**Comment by wdavidw** [comment]
shall be fixed now with 1.1.9

**Comment by tulika-agr** [comment]
Thanks, fixed now.
