### ISSUE TITLE
random blank objects in stream while parsing \r\n line ending

### ISSUE THREAD

**Issue by tarun** [wdavidw/node-csv-parse#125]
I started noticing this with the latest version 1.1.10
while parsing a large stream with 4096 byte chunks - we are getting blank objects randomly.
I guess this is happening when the parse chunk starts with \n (and the previous chunk had a \r).

version 1.1.7 does not have this issue.

Will dig up more details to post here...

**Comment by tarun** [comment]
Looks like that automatic row detector breaks in this scenario.
explicitly passing in `rowDelimiter: '\r\n'` works.

**Comment by tarun** [comment]
This was a breaking change for our application (on a semver patch release)...

Here is a test case:
```coffescript
  it 'handle chunks of multiple chars without quotes in autodiscovery', (next) ->
    data = []
    parser = parse()
    parser.on 'readable', ->
      while d = parser.read()
        data.push d
    parser.on 'finish', ->
      data.should.eql [
        [ 'ABC','45' ]
        [ 'DEF','23' ]
        [ 'GHI','94' ]
        [ 'JKL','02' ]
      ]
      next()
    parser.write 'ABC,45'
    parser.write '\r\nDEF,23\r'
    parser.write '\nGHI,94\r\n'
    parser.write 'JKL,02\r\n'
    parser.end()
```

**Comment by wdavidw** [comment]
shall be fixed now, thanks for reporting
