### ISSUE TITLE
Option to be excelcompatible with ="Text" format

### ISSUE THREAD

**Issue by vIceBerg** [wdavidw/node-csv-parse#127]
Hi!

I have to deal with output from excel. It looks like this:

12345;="Customer Name";="Customer Firstname";="Customer address";987654

The text columns are prepended with = sign.

Is there a way to handle this?

**Comment by wdavidw** [comment]
No natively. I would recommand piping to [transform](https://github.com/wdavidw/node-stream-transform/) to extract/remove the columns.
