### ISSUE TITLE
Is it about node-csv-parse?

### ISSUE THREAD

**Issue by orhankutlu** [wdavidw/node-csv-parse#135]
@wdavidw I am trying to read file with 2.8GB size, parse it and insert it to database. But some point I am having JavaScript heap out of memory error. I have asked it to stackoverflow but couldn't get any answer. Maybe you can let me know what is the issue. I am really stuck with it. Here is my code snippet. (I am using sequelize js, it can be related to it but couldn't find why)
    
    const csvParser = require('csv-parse')

    const Product = require('../models').Product;

    const options = {
        delimiter: '|',
        trim: true,
        relax: true
    }

    const parser = csvParser(options);

    fs.createReadStream('path/to/csv', {encoding: 'utf8'})
        .pipe(parser)
        .on('data', row => {
            processPlainRow(row);
        })
        .on('end', () => {
            console.log('ended');
        })
        .on('error', error => {
            console.log('error: ', error);
        })
        .on('close', error => {
            console.log('stream closed');
        })

    function processPlainRow(row) {
        let productToInsert = parsedRow(row);
        Product
            .create(row)
            .then(product => {
                // do nothing at all
            })
            .catch(error => {
                console.log(error);
            });
    }

    function parsedRow(row) {
        return {
            name: row['name'],
            price: row['price'],
            // ... goes on
        };
    }

**Comment by wdavidw** [comment]
It seems quite normal, you're fonction `on('data', row => { processPlainRow(row); })` is flooded with far more data than what it can handle. If you are using stream (you have to considering the size of your input file), you have to do it all the way in the chain: read file / parse csv / send to db. At the moment, you're missing the last one. you need to put "processPlainRow" in a (Writable stream](https://nodejs.org/api/stream.html#stream_implementing_a_writable_stream). A module like [stream-transform](https://www.npmjs.com/package/stream-transform) can help as well.
