### ISSUE TITLE
Location of coffescript source?

### ISSUE THREAD

**Issue by oleersoy** [wdavidw/node-csv-parse#137]
Is the coffeescript source code available?  I'm attempting to translate it to typescript.

**Comment by wdavidw** [comment]
of course, it's in "./src", why in hell would you do such a thing (joking of course, but interested of the answer, i'm so happy being far away from types as of today)

**Comment by oleersoy** [comment]
Oh Geez - it's embedded in the markdown - That's very cool!  I'm planning on using the parser in a Angular 4 service and I thought it would be great if it could be imported and pruned with rollup the same way RXJS is...Maybe that's allready possible?  I'm still right in the middle of doing a deep dive on all this  Thanks for making the parser - it's really awesome!
