### ISSUE TITLE
[Question] auto_parse behaviour

### ISSUE THREAD

**Issue by kunagpal** [wdavidw/node-csv-parse#141]
Consider the following CSV snippet:
```csv
str, strNum, num
"foo", "1", 2
```
When parsed with `auto_parse` set to true, `"1"` and `2` are converted to their numerical equivalents. Shouldn't `"1"` be left as is, given that it is enclosed in quotes?

**Comment by wdavidw** [comment]
The problem lies in the space before `"1"`, this is not valid csv, we try to handle it with the "relax" option but this option is buggy as of today

**Comment by kunagpal** [comment]
@wdavidw My bad, the spaces were merely for readability. The int casting with `auto_parse` set to `true` happens even without spaces.

**Comment by wdavidw** [comment]
And I didn't really took the time to understand your question, my bad. The casting is not targeting the quote signs, we considere the quote as a CSV thing and not as an information to perform the casting. I'm not saying it is not a good idea but we have to make choices and this is how we do it.

**Comment by kunagpal** [comment]
Alright, is there a workaround here?

**Comment by wdavidw** [comment]
You'll have to cast the value after the parser, for exemple, if using stream and pipe, by using [stream-transform](https://www.npmjs.com/package/stream-transform)
