### ISSUE TITLE
Why escape (char) defaults to double quote?

### ISSUE THREAD

**Issue by anuveyatsu** [wdavidw/node-csv-parse#143]
In the docs, it stated that escape character defaults to `"`:

> * escape (char)
Set the escape character. One character only. Defaults to double quote.

**Comment by wdavidw** [comment]
And what's your problem?

**Comment by anuveyatsu** [comment]
@wdavidw sorry, my initial description of the issue was not coherent. There is `quote` option that also defaults to `"`:

> * quote (char|boolean)
Optional character surrounding a field. One character only. Disabled if null, false or empty. Defaults to double quote.

My guess is these options should be mutually exclusive, otherwise it would have conflicts. For example, at the moment I have a data with following row:

```
...
,MT,MGZ,"Mgarr, Gozo","Mgarr, Gozo",11,AA,1-3-----,1501,,3601N 01417E,
...
```

that is causing following error:

```
Error: Invalid closing quote at line 70547; found "E" instead of delimiter ","
```

**Comment by wdavidw** [comment]
I choose double quote as en escape charactere because It was the most common default value. Quote and escape are not exclusive, look at the [tests](https://github.com/wdavidw/node-csv-parse/blob/master/test/options.escape.coffee#L7-L17).

Now, please send me a complete exemple because yours is working with default options:

```
parse """
,MT,MGZ,"Mgarr, Gozo","Mgarr, Gozo",11,AA,1-3-----,1501,,3601N 01417E,
""", (err, data) ->
  console.log data
```

give

```

parse = require './lib'

parse """
,MT,MGZ,"Mgarr, Gozo","Mgarr, Gozo",11,AA,1-3-----,1501,,3601N 01417E,
""", (err, data) ->
  console.log data
```

**Comment by anuveyatsu** [comment]
The complete example is here - https://github.com/datasets/un-locode/blob/master/data/code-list.csv

However, I just discovered why it was erroring. When I've tried to parse I was getting `Invalid closing quote at line 70547; found "E" instead of delimiter ","`. The reason was extra `"` in the line `70334`.

@wdavidw thank you for your attention and time!

**Comment by brian-murphy** [comment]
Wouldn't it be more user-friendly to have the default escape character be `\`?
