### ISSUE TITLE
Error in samples/pipe.js

### ISSUE THREAD

**Issue by brock** [wdavidw/node-csv-parse#25]
In running through the samples I noticed this error.

`var transform = require('../../stream-transform');`

Stream-transform was not found until I ran npm-install stream-transform then changed the line to this:

`var transform = require('stream-transform');`

EDIT: this is after I cloned the repo and was working out of the project, not using it in another project via npm yet.

**Comment by wdavidw** [comment]
could u point me the link where you saw this code ?

**Comment by brock** [comment]
it is in `samples/pipe.js`

**Comment by wdavidw** [comment]
Thanks

**Comment by brock** [comment]
:+1:
