### ISSUE TITLE
Simple example for reading the data from a source

### ISSUE THREAD

**Issue by yellowiscool** [wdavidw/node-csv-parse#28]
Hi,

I want to read the content of a CSV file, like the first example of the legacy documentation :
```javascript
csv().from.path('/tmp/data.csv').on('data', console.log);
```

I think a similar example with the new API would be very useful. I don't need all these pipes and streams, I just want to read a CSV file :-)

**Comment by wdavidw** [comment]
Yes, i removed whatever wasnt directly related to CSV. However, this is quite easy:

```
fs = require('fs');
parse = require('csv-parse');
fs.readFile('/tmp/data.csv', (err, text){
  parse(text, options, function(err, data){
    console.log(data);
  });
});
```

**Comment by DudleyDawson** [comment]
I feel like this example should be in the documentation. Reading from a source file is the probably the most practical use case for a CSV parser yet it is not in the documentation. Would you accept a PR?

**Comment by wdavidw** [comment]
The [pipe example](http://csv.adaltas.com/parse/examples/) is quite similar but I'm all for adding more examples at the bottom of the page.

In such case, the example should look like:

```fs
fs = require('fs');
parse = require('parse');
fs = createReadStream('./somefile.csv');
fs.pipe(parse(function(err, data){
  data.should.eql([
    [ 'abc', '123' ],
    [ 'def', '456' ]
  ])
}))
```
