### ISSUE TITLE
Dealing with both single- and double-quotes in data

### ISSUE THREAD

**Issue by romeboards** [wdavidw/node-csv-parse#34]
currently using this library on a large dataset where some fields contain various combinations of single and double quotes. some examples:

> ? 27-2005, 2007 ADM CODE FIRE EGRESS DEFECTIVE. REMOVE OBSTRUCTING BARS OR UNLAWFUL GATES FROM WINDOW TO FIRE ESCAPE OR PROVIDE APPROVED TYPE GATE .. IN THE 1st ROOM FROM NORTH AT WEST LOCATED AT APT B32, 3rd STORY, 1st APARTMENT FROM WEST AT NORTH , SECTION "BLDG. "B"", 2nd FROM SOUTH AT WEST

> ? 27-2005 ADM CODE PROPERLY SECURE THE LOOSE WASH/BASIN'S BASE IN THE BATHROOM LOCATED AT APT 6E, 6th STORY, 1st APARTMENT FROM WEST AT NORTH , SECTION AT EAST

the parser seems to fail on conditions such as these with an `Invalid opening quote at line 1`

I've tried modifying the quote and escape options but nothing has ensured that the parser will work on all conditions - am I just doing something wrong?

**Comment by romeboards** [comment]
using `relax: true` seemed to do the trick, apologies. might help to further describe the options a little further, this wasn't super clear

**Comment by romeboards** [comment]
while using `relax: true` prevented any errors from occurring, it seems like these entries were passed over instead of being handled in some way. I tested this on a CSV with 1,894,282 entries; out of those, nearby 50,000 did not seem to be accounted for.

**Comment by wdavidw** [comment]
Could you isolate a simple test case so i can look at it. The "relax" option isnt as strong and tested as the rest of the parser. It more started as a conveniency for non standard CSV code. I'm ready to get back to it if you prepare me a sample or test.

**Comment by cookch10** [comment]
Here's an example that you could start with, which is causing me some trouble:

Data: (first row is the column header, second row is the problematic data, third row is other data which parses fine):

this_name,platform,date,query,impressions,clicks,ctr,avg_position
somename,desktop,2015-01-06,"something,else",1,1,100%,1
other,desktop,2015-01-06,a value,11849,2471,21%,1.7


Using the following parse options:
```javascript
var csvParseOptions = {
    auto_parse: true, // Ensures that numeric values remain numeric
    columns: true,
    delimiter: ',',
    quote: '',
    relax: true,
    rowDelimiter: '\n', // This is an issue, I had to set the \n here as 'auto' wasn't working, nor was 'windows'.  Maybe look at auto-detecting line endings?
    skip_empty_lines: true
};
```

The following illustrates the actual (incorrect) object that is generated alongside the expected object:
```javascript

// The object actually generated by csv-parse.  It's got some problems due to quotes in some of the data:
var observedCSVParseObj = {
    this_name: 'somename',
    platform: 'desktop',
    date: '2015-01-06',
    query: '\'something',
    impressions: 'else\'',
    clicks: 1,
    ctr: 1,
    avg_position: '100%',
    'undefined': 1
};

// This is what the object is expected to look like:
var expectedCSVParseObj = {
    this_name: 'somename',
    platform: 'desktop',
    date: '2015-01-06',
    query: '\"something,else"',
    impressions: 1,
    clicks: 1,
    ctr: '100%',
    avg_position: 1
}
```

**Comment by cookch10** [comment]
As a temporary workaround to the above issue, I've created a stream wrapper that will perform some massaging of the data before piping it to node-csv-parse.  It's a short-term solution, however.

**Comment by wdavidw** [comment]
@cookch10, you're code as double quotes and no single quotes, i'm not sure how it could be related to this issue.

**Comment by cookch10** [comment]
The incoming data itself has quotes in it, which occurs in zero or more field values.  The fields / values themselves are not actually wrapped in any quotes.

**Comment by wdavidw** [comment]
Did you try changing the escape character, csv by convention/specification default to double quote to escape double quote

**Comment by cookch10** [comment]
I have no control over the incoming data, hence the stream wrapper to massage the data.  And with csv, I've found that there's no such thing as specification, it's the wild west.

**Comment by wdavidw** [comment]
specification should be double quoted but escaping with double quote is the standard way to do it across csv libraries, you shall pass the "escape" option, see [this test](https://github.com/wdavidw/node-csv-parse/blob/master/test/escape.coffee#L19-L29)

**Comment by cookch10** [comment]
The test is with a backslash escaped quote, which is not the scenario I am describing.  The quotes in the data are not escaped (no backslash).

**Comment by wdavidw** [comment]
I dont understand what those backslash are here for. They dont do anything in your example. In Javascript, `'\"something' === '"something'` return "true". You agree that I can just disregard them

**Comment by wdavidw** [comment]
@cookch10, looking again at your example, it just cant work since you're setting quote to an empty value. 

Here's a working version:

```coffee
parse """
query
"something,else"
""", columns: true, delimiter: ',', (err, data) ->
  return next err if err
  console.log data
  data[0].should.eql
    query: 'something,else'
  next()
```

My understanding is that you dont want "query" to equal 'something,else' but to equal '"something,else"'. Is this right? If so, then you cant do it at the moment and tweaking the options wont help. we need a new option such as "preserve_quoted_value" or something similiar:

```coffee
parse """
query
"something,else"
""", columns: true, delimiter: ',', preserve_quoted_value: true, (err, data) ->
  return next err if err
  console.log data
  data[0].should.eql
    query: 'something,else'
  next()
```

I'm still not sure if this is related to the original issue, only @romeboards can confirm.

PS, when you submit a sample, please reduce it to its strict minimum.

**Comment by tejasmanohar** [comment]
+1 for `preserve_quoted_value`. Initially, that's what I thought `relax` was.

**Comment by wdavidw** [comment]
not sure it makes much sence, plus we'll need to add the quoted char as an additionnal option. did u really received such a value, if so, u can prepare a pull request and we'll look at it to integrate the option.

**Comment by vkprasadch** [comment]
I'm trying to deal with similar data and facing issues:

Here is my Data:
`1,China Japan Friendship Hospital,中日友好醫院,Beijing,北京,Chao Yang,朝陽區,"No. 2 Yinhua East Road, Hepingli, Chaoyang District, Beijing",北京市朝陽區和平里櫻花園東街2 號,"010-84205566, 010 -64222952, 010-84205288","010-84205566, 010 -64222952, 010-84205288","International Medical Dept., Reception's Cashier Department",國際醫療部

2,Beijing United Family Hospital and Clinics,北京和睦家婦兒醫院,Beijing,北京,Chao Yang,朝陽區,"No. 2 Jiangtai Road, Chaoyang District, Beijing",北京市朝陽區將臺路2 號,"010-59277200, 010-59277120","010-59277200, 010-59277120",Inpatient/Outpatient Cashier Department,住院部/門診部收費處`

I'm trying to parse as follows:

csv.parse({
      columns: true, 
      skip_empty_lines: true,
      trim: true
});

when i run this,

I'm getting 
`Error: Invalid opening quote at line 1`

After reading above, i've tried with relax:true
`
csv.parse({
      columns: true,
      skip_empty_lines: true,
      trim: true,
      relax: true
});
`

So, now error says:

`
Number of columns on line 2 does not match header
`

**Comment by wdavidw** [comment]
Seems to work perfectly fine with me, (with and without options):

```coffee
parse = require 'csv-parse'
parse """
1,Hospital,友好醫院,Beijing,北京,Chao Yang,朝陽區,"No. 2 Yinhua East Road, Hepingli, Chaoyang District, Beijing",北京市朝陽區和平里櫻花園東街2 號,"010-84205566, 010 -64222952, 010-84205288","010-84205566, 010 -64222952, 010-84205288","International Medical Dept., Reception's Cashier Department",國際醫療部
2, Hospital and Clinics,北京和睦家婦兒醫院,Beijing,北京,Chao Yang,朝陽區,"No. 2 Jiangtai Road, Chaoyang District, Beijing",北京市朝陽區將臺路2 號,"010-59277200, 010-59277120","010-59277200, 010-59277120",Inpatient/Outpatient Cashier Department,住院部/門診部收費處
""", (err, data) ->
  console.log err, data
```
