### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by rogierschouten** [wdavidw/node-csv-parse#42]
After CSV parsing I validate the content of the rows. I would like to give my users a line number with any errors that I find.  But unfortunately I cannot count the line numbers myself as empty lines and comment lines are not output by csv-parse. 

Would it be an idea to add a line number property on the array that is received in the on("data") event?

**Comment by wdavidw** [comment]
did you saw the `this.lines` property?

**Comment by rogierschouten** [comment]
Ah great, thanks. I will add it to the TypeScript definitions for csv-parse.

**Comment by rogierschouten** [comment]
No sorry, there is a bug. Comment lines and empty lines are not counted by the lines property and thus it is useless for reporting a location in the CSV file.  Note that I have "skip_empty" set to true.

```javascript
{
		auto_parse: false, // don't convert to native datatypes
		columns: null, // return arrays not objects
		comment: "#",
		delimiter: ",",
		escape: "\"",
		quote: "\"",
		ltrim: true,
		rtrim: true,
		skip_empty_lines: true,
		trim: true
	}
```

**Comment by wdavidw** [comment]
feel free to re-open a third time if not completly fixed

**Comment by rogierschouten** [comment]
Could you publish on NPM please?

**Comment by wdavidw** [comment]
done

**Comment by rogierschouten** [comment]
It works, thank you!
