### ISSUE TITLE
auto_parse boolean literals

### ISSUE THREAD

**Issue by ldegen** [wdavidw/node-csv-parse#45]
Hi,
is anything wrong with parsing boolean literals ('true','false') when `auto_parse` is set?

Please see #44

**Comment by wdavidw** [comment]
there are problems. I'm french and I would expect 'vrai' to cast to `true`. Same goes with an empty string which could cast to `false` or just an empty string which seems much more appropriate.

**Comment by fboutin-pmc** [comment]
@wdavidw ok, and because it doesn't work in french, ` auto_parse` should continue to miserably fail on standard boolean values?

Common, re-open and accept that pull request for God sake.

Thank you,

**Comment by ldegen** [comment]
@fboutin-pmc: Please, tone it down a bit. Everything is cool. :-)

@wdavidw was right to reject my PR. The behavior would have been very specific to the particular way Javascript (and a handful of other programming languages) represent boolean literals.  There are no "standard boolean values" as far as CSV is concerned. You would have to support all sorts of boolean representations for this module to still be functionally 'closed' -- if this makes any sense; I'm afraid I don't know the correct English expression. 

Anyway, if I read the documentation correctly, you can just pass your own application-specific value parser function to `auto_parse`. I think this is quite an adequate solution.

**Comment by wdavidw** [comment]
@ldegen thanks you, you said it all.
