### ISSUE TITLE
delimiter inside quoted fields

### ISSUE THREAD

**Issue by digitalkaoz** [wdavidw/node-csv-parse#48]
the parser fails if there are `delimiter` chars inside quoted strings. e.g.

```csv
"foo";"bar"
"lol;cat";"barf"
```

is there a combination of options to fix this or is it a bug?

this is the parserConfig:

```js
{
    rowDelimiter: "\n"
    delimiter: ";",
    quote: '"',
    escape: '"',
    auto_parse: true,
    columns: true,
    skip_empty_lines: true,
    trim: true,
    relax: true
}
```

**Comment by wdavidw** [comment]
It shall [work](https://github.com/wdavidw/node-csv-parse/blob/master/test/quote.coffee#L20-L32), avoid using "relax"

**Comment by digitalkaoz** [comment]
ok without using relax i got an error and degugged it, it wasnt a `delimiter` inside a quoted string, instead it was something like this:

```
"foo";"bar"
"lol\"c\"at";"barf"
```

using this config, the row get consumed correctly:
{
    rowDelimiter: "\n"
    delimiter: ";",
    quote: '"',
    escape: "\\",
    auto_parse: true,
    columns: true,
    skip_empty_lines: true,
    trim: true,
    relax: false
}

but why do i need to escape `\` ? this char is used to escape the `"`

**Comment by wdavidw** [comment]
According to csv spec, double quotes is the default escape char

**Comment by digitalkaoz** [comment]
yeah but inside quoted string they dont need to be escaped?
