### ISSUE TITLE
Breaking change between 0.0.9 and 0.1.1

### ISSUE THREAD

**Issue by thirdcreed** [wdavidw/node-csv-parse#51]
This is actually a breaking change and so should be a major version update according to the
[ semver spec](http://semver.org/). Specifically number 8 in the 'Semantic Versioning Specification' list.  We noticed this because one of our projects broke because we relied on this assumption.

**Comment by wdavidw** [comment]
dont know what you're talking about, please carify

**Comment by bvinnerd** [comment]
Aren't breaking changes allowed in 0.y.z anyway?

See semver point 4 - assuming @wdavidw is following semver :)

**Comment by wdavidw** [comment]
I still dont know which breaking changes are mentioned. Arount this time, i sent a release with an unexpected and broken change (i forgot that a `git commit` isn't the same as `npm publish` : ) This was not a breaking change, just a mistake as we happen to be human beings.
