### ISSUE TITLE
How to pipe transformed and parsed  csv to JSON object

### ISSUE THREAD

**Issue by mateeyow** [wdavidw/node-csv-parse#52]
Hi, I am trying to parse a csv file like this: 
```
1/03/15 0:15,77.456
1/03/15 0:30,75.76
1/03/15 0:45,78.16
```
having and option `{columns:['dateTime', 'num']}` and transform the object first column into a javascript object by using `moment.js`. So the code should look like this: 
``` javascript
transformer = transform(function (record, cb) {
 record.dateTime = moment(record.dateTime, 'DD/MM/YY h:mm').format();
 cb(null, record);
});
```
And piping the whole code into stream using: `readStream.pipe(parser).pipe(transformer).pipe(writeStream)`
But I'm getting this error:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Invalid non-string/buffer chunk
```
Basically what I want is to 
1. Convert the first column into a correct javascript date object
2. Invoke parser to create an object
3. Save the data to the database (MYSQL).

**Comment by wdavidw** [comment]
where in the piping chain is the problem, does executing `readStream.pipe(parser)` is enough to reproduce the error? seems like readStream emit sth else than buffer or string (object mode?).

by the way, you could simplify transformer:

```
transformer = transform(function (record) {
 record.dateTime = moment(record.dateTime, 'DD/MM/YY h:mm').format();
 return record;
});
```

**Comment by mateeyow** [comment]
@wdavidw The error I'm getting is when I'm writing json object on the writestream

**Comment by wdavidw** [comment]
try:

```
transformer = transform(function (record) {
 record.dateTime = moment(record.dateTime, 'DD/MM/YY h:mm').format();
 return JSON.stringify(record);
});
```

The output will be in json stream format, not 100% JSON, if this is fine with you, otherwise you'll have to find a json transformer package.
