### ISSUE TITLE
`end` event occuring before last `data` event

### ISSUE THREAD

**Issue by derhuerst** [wdavidw/node-csv-parse#59]

**Comment by wdavidw** [comment]
Could you provide a test case or a sample which illustrate this behavior.

**Comment by derhuerst** [comment]
Actually no. I just logged `'end'` whenever `end` occured and logged `'data'` whenever `data` occured.

Sometimes, the last `data` event seems to be triggered before `end`.

**Comment by derhuerst** [comment]
This is weird. It works fine as long as I just put a `console.log` in the `end` handler. Once I do something in there (`deferred.resolve()`), it fails. :weary:

**Comment by wdavidw** [comment]
`console.log` is executed synchronously but i'm not sure this is related. it's important you send me an example.

**Comment by derhuerst** [comment]
As I said, I can't replicate this issue. I tried it with a test CSV file and a test CoffeeScript file but `csv-parse` worked just like expected.

**Comment by wdavidw** [comment]
shall we close it then?

**Comment by derhuerst** [comment]
I must admit it doesn't seem like a general bug, but I still didn't fix it. I will let you know when I know more.

**Comment by derhuerst** [comment]
I fixed it, it was a timing issue with promises. Thansk anyway.
