### ISSUE TITLE
pipe mode - handling rows that span across data bursts

### ISSUE THREAD

**Issue by KrishnaPG** [wdavidw/node-csv-parse#60]
Thank you for sharing this package. I am new to this and have a question.

I need to parse a large http response stream (> 1GB) into csv. Looks like the `pipe` mechanism is a good fit.

I am not sure how the node streams / pipes work, but the chances are every burst of input data may not end at an end-of-line precisely (that is, a row may partially come in first read block, and then rest of the row comes in next read block).

The question I have: is this package capable of handling such scenarios in the pipes mode (where a row may span across two different bursts of input read)?

**Comment by wdavidw** [comment]
Unless u hit a bug, it is expected to handle what u describe
