### ISSUE TITLE
Single-word column names produce invalid JSON key names (no quotes)

### ISSUE THREAD

**Issue by BryonApps** [wdavidw/node-csv-parse#61]
It seems that when using the columns option, column names with single words (no embedded spaces) produce JSON without quotes (columns with embedded spaces work just fine). I played around with the settings and experimented with passing a function in as a columns argument to add the quote, but that does not seem to work...  Here are some captures of what I am seeing:

<img width="432" alt="screen shot 2015-09-02 at 10 33 11 am" src="https://cloud.githubusercontent.com/assets/761461/9635960/8a4de5b0-515e-11e5-8705-f90f742d830d.png">
<img width="398" alt="screen shot 2015-09-02 at 10 33 29 am" src="https://cloud.githubusercontent.com/assets/761461/9635964/8eaa05bc-515e-11e5-9231-00b17e689ce3.png">

Column headers with embedded spaces look fine:

<img width="199" alt="screen shot 2015-09-02 at 10 37 50 am" src="https://cloud.githubusercontent.com/assets/761461/9635993/c4cb581c-515e-11e5-83c1-ae63f523fd0b.png">

<img width="294" alt="screen shot 2015-09-02 at 10 39 22 am" src="https://cloud.githubusercontent.com/assets/761461/9636014/eb400024-515e-11e5-843b-13f77fe2edc8.png">

**Comment by wdavidw** [comment]
a non issue?

**Comment by BryonApps** [comment]
Correct!  Sorry about that!

Bryon Martin

(Sent from my iPhone)
