### ISSUE TITLE
does not parse at all

### ISSUE THREAD

**Issue by david-soyez** [wdavidw/node-csv-parse#63]
```javascript
        csv.parse(yargs.f, {delimiter: ";", quote:'"'}, function(err,output) {
          console.log(output);
        });
```
outputs: [ [ './csv/test.csv' ] ]

How come it does not output the content?
It's been one hour i'm trying to make it work.

**Comment by wdavidw** [comment]
you have an error ? `console.log(err, output);`

**Comment by david-soyez** [comment]
no error:
null [ [ './csv/test.csv' ] ]

**Comment by wdavidw** [comment]
u'll need to be more precise, what is "yargs.f"

**Comment by david-soyez** [comment]
yargs.f is the filename from command line argument, I tried with the filepath directly but same no nothing.
node v0.10.25
the csv content is
"aa";"bb";"cc";"dd"

**Comment by wdavidw** [comment]
U need to pass the content, not the filename

**Comment by david-soyez** [comment]
oops thank you
I thought we could do both because most of the module do it.
