### ISSUE TITLE
What about synchronous syntax?

### ISSUE THREAD

**Issue by yisk** [wdavidw/node-csv-parse#66]
I'm loading the csv-data at server startup. I don't want any asynchronous behaviour in that case. Is it possible to process all of data synchronously?

**Comment by wdavidw** [comment]
Technically yes. However, you would have to instantiate `require('csv-parse').Parser` yourself

**Comment by jameshiew** [comment]
It's useful in some cases to block until all the data has been parsed. Would you have a simple example of how to instantiate `Parser` to do this?

**Comment by wdavidw** [comment]
I dont have time to test but calling "__write" (with the end argument as true) after instantiating the Parser shall do the job

**Comment by jameshiew** [comment]
Thanks, I didn't manage to get it to work, (couldn't find the `.__write` method on a `new require('csv-parse').Parser()`), but I think a `.parseSync()` method of some sort would be a useful addition to the API.

**Comment by amykyta** [comment]
I tried `parser.write(data, true)` and then read the data from the stream in a loop with `parser.read()`. This works but the last row of csv data is missing for some reason.

**Comment by wdavidw** [comment]
Can send me ehat u got, ill consider implementing this feature.

**Comment by amykyta** [comment]
Sure, but it's a hack. I doubt all the options work (like columns for example). I just needed the array version. 
```javascript
function csvParseSync(csvData, options){
	var csvParser = new csvParse.Parser(options);
	csvParser.write(csvData, true);

	var parsedData = [];
	var chunk;
	while(chunk = csvParser.read()){
		parsedData.push(chunk);
	}

	return parsedData;	
}
```

**Comment by wdavidw** [comment]
sync api is implemented inside './lib/sync', look at the './test/sync.coffee' test.
