### ISSUE TITLE
Date Detection is a Bit Fubar

### ISSUE THREAD

**Issue by jherdman** [wdavidw/node-csv-parse#71]
Date-y strings are being parsed :( Reproduction https://github.com/jherdman/node-csv-parse/blob/5b52d6087dacb4b18ef747c768f673763c8c2c4f/test/options.auto_parse_date.coffee

**Comment by wdavidw** [comment]
what's so wrong about it? what do u suggest?

**Comment by jherdman** [comment]
I'm parsing a CSV of wine products, just about every name has the vintage of the wine (e.g. "2013 Malbec"). JavaScript's Date parsing is kind of stupid, it'll see "2013" and assume that this is a date string, and dutifully give you an integer which you can then turn into a date object. More details http://blog.dygraphs.com/2012/03/javascript-and-dates-what-mess.html.

I don't think you really want to find yourself trying to program a strict date parser, that'd be a path to sadness. Perhaps a solution would be to have per-column parsing opt-in. Using such an approach I could indicate which columns definitely contain date fields, and which I'd want skipped.

**Comment by wdavidw** [comment]
Option like "auto_parse" and "auto_parse_date" are helper and shouldn't be considered industrial. I would personnaly not use them in production but use [transform](http://csv.adaltas.com/transform/) instead.
