### ISSUE TITLE
Fails to parse newline correctly

### ISSUE THREAD

**Issue by JonathanMH** [wdavidw/node-csv-parse#72]
Hi, I'm on version `1.0.0` and it doesn't parse my newlines correctly (I think).

Assuming I have a .csv file that contains the following (from a readable fs stream):
```
Name,Gender,"preferred language",startDate,endDate
Barbara McFinley,Female,JavaScript,2015-13-01,,
```
my output file would be empty (assuming your standard streaming example)

* If I insert a newline at the beginning of the file (first line empty) it works correctly
* If I insert **two spaces** (really, one doesn't work) on a line before the last empty line, it works correctly

(this is true for LF and CRLF options)

I'm using the atom editor, so it adds a newline at the end of the file, which I think should be enough, shouldn't it?

Correct output:
```
Name,Gender,preferred language,startDate,endDate
Barbara McFinley,Female,JavaScript,2015-13-01,,
```

Gist with some code and example file:
https://gist.github.com/JonathanMH/27b2e293cec1647f16c7

**Comment by JonathanMH** [comment]
I've done some debugging and ending the parser stream manually after my readable stream from the file ends, fixes the issue!

I can't evaluate if this should be documented somewhere or if it's just the way streams work, but I guess it would be nice to have this in the examples. For reference, it's `index2.js` in the gist: https://gist.github.com/JonathanMH/27b2e293cec1647f16c7

**Comment by wdavidw** [comment]
I would say (but could be wrong) that it came from a misuse of the stream api. you're using stream manually so it is your responsibility to propagate the end event. a simpler and safer usage of your code is with pipe:

```js
// This doesnt change
var fs = require('fs');
var csv = require('csv');
var readableStream = fs.createReadStream('employee.csv');
var parser = csv.parse();
var transformer = csv.transform(function(data){
  return data.map(function(value){return value.toUpperCase()});
});
var stringifier = csv.stringify();
// This does the work
readableStream.pipe(parser).pipe(transformer).pipe(stringifier).pipe(process.stdout);
```

**Comment by JonathanMH** [comment]
Yes, my code looks a lot different, but I wanted to illustrate it with the boilerplate code and it's probably quite common that people will read a .csv file, which is why an improvement to the docs might be a good idea. I can not find them on github though, so I assume they're part of the company website somewhere.

**Comment by wdavidw** [comment]
I would always recommand using the pipe strategy, working with the native event/stream api is quite complicated to get right. Are u mentioning the doc on [docs.adaltas.com](http://docs.adaltas.com)? They can be found [on github](https://github.com/wdavidw/node-csv/tree/master/doc).
