### ISSUE TITLE
Support optional header lines

### ISSUE THREAD

**Issue by ZoltanLajosKis** [wdavidw/node-csv-parse#75]
It seems csv-parse assumes that if I specify a columns function, then the first line in the input is a header line. Even if the function returns null, the first line is consumed and not emitted as data.

It would be nice if the columns function could also signal with its return value that:
1) no, the first line wasn't a header, just use it as data, and don't use column names (parse into array)
2) no, the first line wasn't a header, just use it as data, and use the following column names

I have the following workaround to simulate 2), but it looks ugly and fragile:

``` js
let cs = csv.parse({
  columns: (firstLine) => {
    if (isHeaderLine(firstLine)) {
      return firstLine;    // first line indeed contains column names
    }

    const cols = ["Col1", "Col2", "Col3"]; // use these column names

    let firstData = {}; // and use first line as regular data
    for (let i=0; i < Math.min(cols.length, firstLine.length); i++) {
      firstData[cols[i]] = firstLine[i];
    }

    cs.push(firstData);
    return cols;
  }
});

fs.createReadStream("test.csv").pipe(cs);
cs.on('data', function (data) { console.log("DATA", data) });
```

**Comment by wdavidw** [comment]
Thanks for reporting this, if you have the time, you could provide a patch.

**Comment by keyscores** [comment]
Not sure if this is in the same scope:
There are many systems that export a csv with a few rows of metadata:
Consider a Google Play export:

    ï»¿Per Transaction Report					
    Reporting Period: 	2014-01-01 to 2014-01-31				
    Native Retail Currency: 	USD				
    Country, Transaction, Date,	Name of App
    Usa, 24234jh24, 1/1/14, "App Name"

Is there any way to achieve this currently? 

I suggest a param like {skipToHeader: 4 } , to start from the 4th row.

**Comment by wdavidw** [comment]
I would suggest opening a new issue as this seems like a new feature. I would make sense.

**Comment by wdavidw** [comment]
There are now to new options: "from" and "to". This partially fix this issue, no completly. Closing, feel free to re-open if necessary
