### ISSUE TITLE
How to use the parameter 'rowDelimiter'

### ISSUE THREAD

**Issue by liqili** [wdavidw/node-csv-parse#77]
Hi,
I want to use ‘\n’ to delimit record rows,but I meet issue when parsing the csv file.Below is my code.
`{rowDelimiter:'\n',...}`
How to use the parameter correctly?
rowDelimiter (chars|constant)
String used to delimit record rows or a special value; special constants are 'auto', 'unix', 'mac', 'windows', 'unicode'; defaults to 'auto' (discovered in source or 'unix' if no source is specified).

**Comment by wdavidw** [comment]
sorry i forgot to answer your issue. if you're have trouble, the [tests](https://github.com/wdavidw/node-csv-parse/blob/master/test/rowDelimiter.coffee) are probably the illustration of usage.

**Comment by liqili** [comment]
Thanks,it will be great help to me．
