### ISSUE TITLE
Default comment character is not set

### ISSUE THREAD

**Issue by joekrill** [wdavidw/node-csv-parse#78]
According to the documentation (http://csv.adaltas.com/parse/) the option `comment` defaults to '#', but that is not accurate -- there is no default set for this in the code (see https://github.com/wdavidw/node-csv-parse/blob/master/lib/index.js#L106). Should the code be updated to reflect the documentation, or the documentation be updated to reflect the current behavior?

**Comment by wdavidw** [comment]
I would answer the code is the most accurate documentation: ). I'll update the documentation. Thanks for pointing this out.
