### ISSUE TITLE
`fromRow` option support

### ISSUE THREAD

**Issue by hbakhtiyor** [wdavidw/node-csv-parse#84]
would be nice to add `fromRow` option support which parse from the desired line number

**Comment by wdavidw** [comment]
This seems similar to #81 which was recently raised

**Comment by wdavidw** [comment]
closing, feel free to re-open if necessary

**Comment by wdavidw** [comment]
I ended up implemented it with to "from" and "to" options

**Comment by Zodiase** [comment]
@wdavidw `from` doesn't seem to affect header column parsing.
