### ISSUE TITLE
`zipRaw`

### ISSUE THREAD

**Issue by AGhost-7** [wdavidw/node-csv-parse#85]
I was thinking that it would be nice to be able to see the original data along with the parsed row. So instead of getting an array for each row you'd get either a two dimensional array where the first element is the raw string and the second is the parsed row. Could be a separate function or an option.

**Comment by wdavidw** [comment]
if you feel like implementing it, i'm not against the idea

**Comment by AGhost-7** [comment]
I'll give it a try some time; it would help debugging if the third party provided correct data in our case.

**Comment by wdavidw** [comment]
seems like we could close that one after #88 being merged.
