### ISSUE TITLE
Multiple escape values?

### ISSUE THREAD

**Issue by tejasmanohar** [wdavidw/node-csv-parse#91]
@wdavidw Is it possible to set multiple escape values with this module? Reading [here](https://success.salesforce.com/ideaview?id=0873000000080jnAAA), Salesforce suggests escaping `"\"", "\"\""` for their CSVs- not sure what the best way to accomplish that is with this lib.

**Comment by wdavidw** [comment]
unless you change the default value, csv escape by default with a double quote. you can refer at the [escape test](https://github.com/wdavidw/node-csv-parse/blob/master/test/escape.coffee)

**Comment by tejasmanohar** [comment]
Ah I see. Could [double-double quotes](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/datafiles_csv_valid_record_rows.htm) cause issue?

**Comment by tejasmanohar** [comment]
Maybe that should be set as an escape character?

**Comment by tejasmanohar** [comment]
Either way, curious if we can set multiple escape characters (like an array of them) rather than just one? Thanks for all the help, btw. :)

**Comment by wdavidw** [comment]
I dont think it's possible. Not completly sure because there are such option which can now be multiple characters but i dont think escape is one of them.
