### ISSUE TITLE
trim option does not work on quoted CSV files

### ISSUE THREAD

**Issue by zam6ak** [wdavidw/node-csv-parse#92]
Consider following example file:

```csv
"account_no","first_name","last_name"
"001","HOMER","SIMPSON"
"002","MICKEY","MOUSE"
"003","BENDER","ROBOT"
```

and following parser options:
```typescript
const csvParserOptions: csvParse.ICsvParseOpts = {
    delimiter: ',',
    rowDelimiter: '\r\n',
    quote: '"',
    columns: true,
    skip_empty_lines: true,
    trim: true,
    auto_parse: false
};
```

If I modify the first_name of the second record and add spaces before, after or both, I get different results.In two cases, I get errors:
```
with leading and trailing spaces (...,  "MICKEY"  ,...) 
	"Invalid closing quote at line 3; found " " instead of delimiter ",""

with leading space (..., "MICKEY",...) 
	No error !!!

with trailing space (...,"MICKEY"  ,...) 
   "Invalid closing quote at line 3; found " " instead of delimiter ",""
```

Same file, **_without quotes_** has no issue at all....

Any ideas?

**Comment by wdavidw** [comment]
This CSV is invalid, trim is expected to work on valid CSV data, meaning with quotes next to field delimiters. Said differently, trim is working inside you're quote. What you want is relax. A few months ago, i tried to implement relax to trim outside of quotes. It happened to be much more complicated than expected. I reverted my work after 2 hours as it was getting late. Not impossible, but hard.

**Comment by zam6ak** [comment]
Hmm...Why is CSV invalid if all the elements are quoted?
CSVLint reports ok on those records...

I also tried `trim: true` on `(...,"  MICKEY   ",...) ` and it didn't trim the spaces inside....

**Comment by wdavidw** [comment]
because you're not supposed to have space between field separator and quotes. Now, this being said, i'm totally ok for supporting it, this is a task for the relax option but, as i wrote you earlier, I failed last time i tried implementing it.
