### ISSUE TITLE
Parse a stream of lines

### ISSUE THREAD

**Issue by bitdivine** [wdavidw/node-csv-parse#95]
Hello,

How should I go about reading a stream of lines?  I have files, not all of which are CSV, so I open a file as a stream, split it into lines, filter out the ones that aren't csv, then I would like to pipe the lines into your parser, however when I do that the code simply hangs.  I don't see an option that would help.  The code looks something like this:

    var split = require('split');
    var csv = require('csv-parser');
    var sf = require('stream-filter');
    fs.createReadStream(....)
        .pipe(split())  // split the data into lines
        .pipe(sf((data)=>true) // The real function is more complicated :-)
        .pipe(csv())
        .on('data', (record) => console.log('hooray:', JSON.stringify(record)));

Many thanks!

Max

**Comment by wdavidw** [comment]
you need a tream stream reader on the other to behave as a pump (you can use the stream-transformer project with the consume option activated).
