### ISSUE TITLE
Stream API: readable not emitted until next line or end

### ISSUE THREAD

**Issue by yoursunny** [wdavidw/node-csv-parse#96]
Use case: I have a network socket that receives one line of CSV at a time. The socket is piped into a CSV parser. It's desirable that the CSV parser emits 'readable' event as soon as '\n' is received, so that downstream program can process the record as soon as possible.
However, the CSV parser doesn't emit 'readable' until either the next line is received, or until the socket is closed (which calls `.end` on the CSV parser's transform stream).

Snippet to reproduce:
```
var csv = require('csv');
var parser = csv.parse();
parser.on('readable', function(){
  var row;
  while (row = parser.read()) {
    console.log(row.join(','));
  }
});
console.log('line1 before');
parser.write('A,B,C\n');
console.log('line1 after');
console.log('line2 before');
parser.write('D,E,F\n');
console.log('line2 after');
console.log('end before');
parser.end();
console.log('end after');
```

Expected output:
```
line1 before
A,B,C
line1 after
line2 before
D,E,F
line2 after
end before
end after
```

Actual output:
```
line1 before
line1 after
line2 before
A,B,C
line2 after
end before
D,E,F
end after
```

**Comment by wdavidw** [comment]
The parser itself doesnt emit any event and just implement the Node.js stream api as a good citizen. I would probably discharge myself on Node.js as responsible to this behavior unless there is a way to influence it.

**Comment by yoursunny** [comment]
**byline**, also implemented as a Transform stream, emits a 'readable' event as soon as '\n' is received.
```
var byline = require('byline');
var bylineTransform = byline();
var StringDecoder = require('string_decoder').StringDecoder;
var decoder = new StringDecoder('utf-8');

bylineTransform.on('readable', function(){
  var row;
  while (row = bylineTransform.read()) {
    console.log(decoder.write(row));
  }
});

console.log('line1 before');
bylineTransform.write('A,B,C\n');
console.log('line1 after');
console.log('line2 before');
bylineTransform.write('D,E,F\n');
console.log('line2 after');
console.log('end before');
bylineTransform.end();
console.log('end after');
```

This gives:
```
line1 before
A,B,C
line1 after
line2 before
D,E,F
line2 after
end before
end after
```

Thus, I'm still suspecting a problem within csv-parse. I'm reading the code, and I'll post more information when I understand the logic better.

**Comment by yoursunny** [comment]
It seems that Node.js is passing the whole string ending with '\n' to `__write`, but `__write` somehow leaves the last few chars in `buf` instead of trying to parse it.

```
var csv = require('csv');
var parser = csv.parse();

parser.__write2 = parser.__write;
parser.__write = function(chars, end, callback) {
  console.log('__write(' + escape(chars) + ',' + (end ? 't' : 'f') + ')');
  parser.__write2(chars, end, callback);
  console.log('.buf=' + escape(this.buf));
};

parser.__push2 = parser.__push;
parser.__push = function(line) {
  console.log('__push([' + line.join(',') + '])');
  parser.__push2(line);
};

parser.on('readable', function(){
  var row;
  while (row = parser.read()) {
    console.log(row.join(','));
  }
});
console.log('line1 before');
parser.write('A,B,C\n');
console.log('line1 after');
console.log('line2 before');
parser.write('D,E,F\n');
console.log('line2 after');
console.log('end before');
parser.end();
console.log('end after');
```

This gives:
```
line1 before
__write(A%2CB%2CC%0A,f)
.buf=C%0A
line1 after
line2 before
__write(D%2CE%2CF%0A,f)
__push([A,B,C])
A,B,C
.buf=%2CF%0A
line2 after
end before
__write(,t)
__push([D,E,F])
D,E,F
.buf=
end after
```

I think `buf` should only be used if the rest of input `chars` is an incomplete line (or an incomplete field).

**Comment by yoursunny** [comment]
I poked around the `__write` function. It seems that commenting out the `break` statement [here](https://github.com/wdavidw/node-csv-parse/blob/f0629632af31944eb7cb86f74a6786f91f109268/lib/index.js#L278-L280) makes things work, although I don't know the implication elsewhere.

**Comment by wdavidw** [comment]
this library is strongly tested and follow the phylosophie "if not tested then not supported" so u shall feel confident to introduce changes as long as `npm run coffee && npm test` work, I'll review them

**Comment by yoursunny** [comment]
I will try, but not until I understand how to pour that "coffee".

**Comment by wdavidw** [comment]
shouldnt be too hard, same as javascript, just without the crap

**Comment by hakatashi** [comment]
I got the same problem. I'll work for this and send a PR in a week.
